git clone https://github.com/JLU-OSTA/ChangeNumToAnySystem.git
git clone https://github.com/JLU-OSTA/CPrimerPlus_myAnswers.git
git clone https://github.com/JLU-OSTA/matrix_row_simplify.git
git clone https://github.com/JLU-OSTA/SinMusic.git
git clone https://github.com/JLU-OSTA/MCU-SerialPortAssistant.git
git clone https://github.com/JLU-OSTA/OSTA_LEDSegmentDisplays_HeaderFile.git
git clone https://github.com/JLU-OSTA/OSTA_ASM.git
git clone https://github.com/JLU-OSTA/OSTA_MCU_HeaderFile.git
git clone https://github.com/JLU-OSTA/Arduino_Virtual_USB.git
